baseURL = "www.satu.co.nz"
languageCode = "en-us"
title = "Stars and the Underground"
theme="ananke"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 3

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 3

[[menu.main]]
  identifier = "shows"
  name = "Shows"
  url = "/shows/"
  weight = 3

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  identifier = "releases"
  name = "Releases"
  url = "/releases/"
  weight = 3

[[menu.main]]
  identifier = "video"
  name = "Video"
  url = "/video/"
  weight = 3
  
[[menu.main]]
  identifier = "press"
  name = "Press"
  url = "/press/"
  weight = 3

[params.logo]
  url = "logo.jpg"
  width = 50
  height = 50
  alt = "Logo"